version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/payments
      JWT_SECRET: verysecretjwtkey
      WEBHOOK_SECRET: gfdmhghif38yrf9ew0jkf32
      INIT_DB: "1"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

volumes:
  pgdata:
